Bookstore: Initialize app
smunozmo/bookstore-react-redux pull request #1
Opened 2021-08-24 17:04 UTC by smunozmo

# Documentation

All the documentation is on the README file.

## Updates:

*  Set up initial files and components.
*  Added React router for every link.

## Notes:

✅  - Used  React.
✅  - Used  Redux.
✅  - Used  React router.
✅  - No linters errors.

2021-08-24 19:58 UTC, dasileker requested changes
### **Hi @smunozmo**, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-24 19:58 UTC, dasileker commented on package.json
> +    "react-bootstrap": "^2.0.0-beta.5",
- [ ] As the requirement says you need to add the redux see the screenshot 👇


![b](https://user-images.githubusercontent.com/61562626/130681473-db37ae51-e733-4677-9a5b-3db281539bd8.jpeg)

2021-08-25 14:27 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @smunozmo  🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-25 14:55 UTC, smunozmo commented
Thank you @mricanho @dasileker

2021-08-25 14:56 UTC, merged